### ISSUE TITLE
NetFx 3.5 and 4.0 compatibility

### ISSUE THREAD

**Issue by PhenX** [martinjw/dbschemareader#104]
Hello, this is more a question than an issue, but I'd like to know if the compatiblity with those framework versions is something worse keeping or if you are planning to make the main project (DatabaseSchemaReader.csproj) full netstandard ?
I yes, I could try and port a maximum of code to each version you want to keep.

**Comment by martinjw** [comment]
The project has 5 different builds: net35, net40, net45, netstandard 1.5 and netstandard 2.0. All are included in the nuget package. 

Occasionally I build on a new machine and it fails because 3.5 isn't installed, but I still have a net35 application that uses it; it will never be upgraded but it is still in use. 

Unless there's a major rewrite, I plan to keep all the versions going.
