### ISSUE TITLE
ForeignKeyColumnName as Column property

### ISSUE THREAD

**Issue by tstaa** [martinjw/dbschemareader#19]
In the column properties we have **ForeignKeyTableName** which very useful information, I think it would be even better if we can have **ForeignKeyColumnName** as well, at the moment I actually run a separate query just to retrieve that information.
Thanks.

**Comment by martinjw** [comment]
The simple case is straightforward, because we link up the foreign key table, and a foreign key is normally pointing to the primary key.
`var fkColumnName = column.ForeignKeyTable.PrimaryKeyColumn`

It's not so easy when the columns are part of composite keys (and the column could be part of multiple foreign keys- that's why there is both a ForeignKeyTableName and a ForeignKeyTableNames list). Rarely, the foreign key points to a unique constraint instead of the primary key. All that information is available if you look through the foreign keys collection of the table. I'll think about the design, maybe we can come up with an easier way to navigate it.

**Comment by tstaa** [comment]
ForeignKeyTable always seems to be null, so I cant get the info the way you just mentioned.
And in my case the referenced column is not always the primary key column.
No worries, it was just an idea, thanks for this great library.
