### ISSUE TITLE
Foreign Key pre-loading and performance

### ISSUE THREAD

**Issue by phusband** [martinjw/dbschemareader#2]
The SchemaConstraintLoader.cs constructor pre-loads the foreign key constraints passing a null tablename to the CheckConstraints method.  Since a null tableName effectively makes the SQL command table agnostic, the constraints returned will be for all tables in the database.   In a typical database that has foreign keys, this load happens once in the constructor call, and is loaded thereafter from the cached constraints (SchemaConstraintLoader.cs Line 69).

However the problem arises when a database has no foreign keys at all.  When a database without foreign keys pre-loads the foreign keys, no results are returned.  Thus, in the foreach loop spanning all database tables in the DatabaseReader.AllTables() method, loading foreign key constraints tries to load the constraints for every single table, which will always return no results.  In the case where foreign key pre-loading returns no foreign key constraints, shouldn't the assumption be that no foreign keys exist?
if (_noFks) return null;

On a SQL Server database with 250 tables (and no foreign keys), this dramatically changed execution time:

Before
![image](https://cloud.githubusercontent.com/assets/3700738/8958823/bee98160-35cc-11e5-9a57-fd94936095cf.png)

After
![image](https://cloud.githubusercontent.com/assets/3700738/8958891/3b1beef8-35cd-11e5-905e-cb9a9e0e0d5a.png)

**Comment by martinjw** [comment]
A relational database with no foreign keys? Eek
But I have seen more than a few databases like that :wink: 

There is a reason for that pattern- try to load all data (null for tablename)/ if nothing found, try to load data for specific tables. On some databases for certain metadata we can't get the data for all tables - you have to specify the table. 

Having said that, for foreign keys (and constraints in general) I believe all our supported databases always have the "all table" version. So that's a safe optimization to make.

**Comment by phusband** [comment]
Yeah, this particular database model is not ideal, however I'm stuck with it for now since it's a product we heavily support.  

Good to know in regards to the extra meta-data coming in, that's an understandable approach.  This check might apply in a few other constraints as you said, so a few more small performance gains might be possible (at least with a model similar to the one I'm running).

Great repo by the way.
