### ISSUE TITLE
SqlServer.ConstraintWriter has "primary key magic"

### ISSUE THREAD

**Issue by hmmueller** [martinjw/dbschemareader#32]
The SqlGen Code in SqlServer.ConstraintWriter.WritePrimaryKey mixes two completely unrelated, orthogonal concepts, namely the UNQIUEIDENTIFIER column type and the concept of CLUSTERED/NONCLUSTERED index. This is unfortunate because it creates wrong SQL when comparing schemas.
I suspect that a native support of CLUSTERED/NONCLUSTERED would be helpful, as not only SqlServer has These concepts (even though they are not as prominent with other DBs).

(As we use my fork of DbSchemaReader, this is not a high-prio item - rather an informal notice that this is a design that will probably break in many use cases).

H.M.

**Comment by martinjw** [comment]
The clustered index concept is a little different between the databases.. PostgreSql allows you to cluster a table, but it's a one-off operation and the index isn't maintained. In Oracle there's different terminology ("index oriented tables" - IOT, and it's on table, not index - appropriately, I think). MySql InnoDb tables are always clustered by PK or UK, there's no control of it.
The fix saves PRIMARY NONCLUSTERED indexes in Index.IndexType, and obeys it in SqlGen, rather than trying to impose best practice on guids (a bit of logic left over from an application I used it on many years ago...!)
