### ISSUE TITLE
MigrationGenerator.AddColumn always adds default

### ISSUE THREAD

**Issue by rufio620** [martinjw/dbschemareader#59]
The migration generator displays some strange behavior in that it always adds a default '' for string columns. There are many cases where this is not desirable behavior. It seems like the default should be left off completely if the default valueis null and include it if it evaluates to a value or string.empty. The constraints generated by this do not always get dropped correctly when a column is changed as well.

The follow code from the method demonstrates the issue.

```c#
      if (string.IsNullOrEmpty(databaseColumn.DefaultValue) && !databaseColumn.Nullable)
      {
        DataType dataType = databaseColumn.DataType;
        if (dataType == null || dataType.IsString)
          str += " DEFAULT ''";
        else if (dataType.IsNumeric)
          str += " DEFAULT 0";
        else if (dataType.IsDateTime)
          str += " DEFAULT CURRENT_TIMESTAMP";
        str = str.Replace(" NOT NULL ", " ") + " NOT NULL";
      }
```

**Comment by martinjw** [comment]
This is for NOT NULL columns. You can't add a column with a NOT NULL constraint to an existing column- in sql server the error is 4901 

> ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Column 'a' cannot be added to non-empty table 'x' because it does not satisfy these conditions.
 
There are some conditions in that message which we don't test (empty tables, identity columns), but this will vary by database platform. We add a default empty string because it's the easiest quick fix, but in most cases it would be a business decision whether there is a suitable default, or the table should be dropped and recreated, or some add nullable/update/make not null script - not things we can automate! 

I think we're doing the right thing- does it make sense to you?

**Comment by rufio620** [comment]
This makes sense and is  correct in the majority of cases. I am just running into an edge case where it is not technically the desired behavior. It only really manifested because for some reason the change column data type migration was not correctly dropping the default constraint when switching the column to null. Let me dig into that issue and see if I can reproduce it. If so I can open another issue to see what can be done about that. Thanks for the quick reply.
