### ISSUE TITLE
Questions about testing connection and design

### ISSUE THREAD

**Issue by codenesium** [martinjw/dbschemareader#65]
I spent a lot of time writing my own version of your project that I thought was great and then I found your project and trashed it all because yours is so much better in every way. Thanks for making and maintaining this.

I'd ask these directly but I don't see any contact info.

1. Is there anything in this project that would test if you are able to connect to the database with a supplied connection string? I poked around but nothing jumped out to me.

something like this 
`public bool TestConnection(string connectionString, string provider);`

2. From a design perspective I'm curious why you chose to name the class that represents the whole database DatabaseSchema instead of DatabaseContainer or something. And then under that you have DatabaseDbSchema. Then your tables are stored in DatabaseSchema and the DatabaseDbSchema is separate. I would expect the tables to be contained inside the schema object and all of the schemas to be inside the container object. If there is not reason that's ok I just want to be sure there's not some big picture database idea I'm missing.

Thanks!

**Comment by martinjw** [comment]
Glad our project helps you!

1. In the integration tests, there's a ProviderChecker.Check(provider, connectionString) that does exactly this. In the main library you generally want the raw exception so you know why you can't connect, but in tests I just needed to make the test inconclusive as the database wasn't running on that machine.

2. "DatabaseSchema" is properly something like "Catalog", a container of schemas. Most database designs have a single schema (in SqlServer, "dbo"), so we didn't want to add that extra level when most of the time it isn't used. In some databases there is no catalog/schema layer- just the database (MySql, SQLite). And in Oracle you have the overlapping concept of "Owner" (which is why this library tends to use "SchemaOwner"). So... we used the colloquial if not strictly accurate term "DatabaseSchema".

Then... we found the need to have a simple list of schemas (true schemas). So "DatabaseDbSchema" was added. Which is a little awkward, I know!

**Comment by codenesium** [comment]
Thanks that was what I was looking for on the connection test.

On the Schema question hat was kind of what I was expecting. I have a product where I'm generating a .NET core rest api for a database and your library will (I hope) let me make it multi database compatible. I will probably have a database schema creator that I base on your library that lets you build a database quickly and generate the scripts for different databases. I'll open source that part of it and link back you. Thanks again.
